/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LocationSegments, MatchResults, RouterHistory, } from "@stencil/router";
export namespace Components {
    interface AppGame {
        "history": RouterHistory;
        "location": LocationSegments;
        "match": MatchResults;
    }
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppToolbar {
    }
    interface HoButton {
        "onClick": Function;
    }
    interface HoGameActive {
        "game": any;
    }
    interface HoGameCard {
        "game": {
            name: string;
            data: string;
            key: string;
        };
    }
    interface HoGameList {
    }
}
declare global {
    interface HTMLAppGameElement extends Components.AppGame, HTMLStencilElement {
    }
    var HTMLAppGameElement: {
        prototype: HTMLAppGameElement;
        new (): HTMLAppGameElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppToolbarElement extends Components.AppToolbar, HTMLStencilElement {
    }
    var HTMLAppToolbarElement: {
        prototype: HTMLAppToolbarElement;
        new (): HTMLAppToolbarElement;
    };
    interface HTMLHoButtonElement extends Components.HoButton, HTMLStencilElement {
    }
    var HTMLHoButtonElement: {
        prototype: HTMLHoButtonElement;
        new (): HTMLHoButtonElement;
    };
    interface HTMLHoGameActiveElement extends Components.HoGameActive, HTMLStencilElement {
    }
    var HTMLHoGameActiveElement: {
        prototype: HTMLHoGameActiveElement;
        new (): HTMLHoGameActiveElement;
    };
    interface HTMLHoGameCardElement extends Components.HoGameCard, HTMLStencilElement {
    }
    var HTMLHoGameCardElement: {
        prototype: HTMLHoGameCardElement;
        new (): HTMLHoGameCardElement;
    };
    interface HTMLHoGameListElement extends Components.HoGameList, HTMLStencilElement {
    }
    var HTMLHoGameListElement: {
        prototype: HTMLHoGameListElement;
        new (): HTMLHoGameListElement;
    };
    interface HTMLElementTagNameMap {
        "app-game": HTMLAppGameElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-toolbar": HTMLAppToolbarElement;
        "ho-button": HTMLHoButtonElement;
        "ho-game-active": HTMLHoGameActiveElement;
        "ho-game-card": HTMLHoGameCardElement;
        "ho-game-list": HTMLHoGameListElement;
    }
}
declare namespace LocalJSX {
    interface AppGame {
        "history"?: RouterHistory;
        "location"?: LocationSegments;
        "match"?: MatchResults;
    }
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppToolbar {
    }
    interface HoButton {
        "onClick"?: Function;
    }
    interface HoGameActive {
        "game"?: any;
    }
    interface HoGameCard {
        "game"?: {
            name: string;
            data: string;
            key: string;
        };
    }
    interface HoGameList {
    }
    interface IntrinsicElements {
        "app-game": AppGame;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-toolbar": AppToolbar;
        "ho-button": HoButton;
        "ho-game-active": HoGameActive;
        "ho-game-card": HoGameCard;
        "ho-game-list": HoGameList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-game": LocalJSX.AppGame & JSXBase.HTMLAttributes<HTMLAppGameElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-toolbar": LocalJSX.AppToolbar & JSXBase.HTMLAttributes<HTMLAppToolbarElement>;
            "ho-button": LocalJSX.HoButton & JSXBase.HTMLAttributes<HTMLHoButtonElement>;
            "ho-game-active": LocalJSX.HoGameActive & JSXBase.HTMLAttributes<HTMLHoGameActiveElement>;
            "ho-game-card": LocalJSX.HoGameCard & JSXBase.HTMLAttributes<HTMLHoGameCardElement>;
            "ho-game-list": LocalJSX.HoGameList & JSXBase.HTMLAttributes<HTMLHoGameListElement>;
        }
    }
}
